[PHP]
extension_dir = "ext"
date.timezone = "Europe/Kyiv"
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
error_log = "C:/WPronto/src/WPLaunchGUI/bin/Debug/net8.0-windows/logs/php_error_8.3.log"

upload_max_filesize = 256M
post_max_size = 256M
memory_limit = 512M
max_execution_time = 600
max_input_time = 600
max_input_vars = 5000

extension=curl
extension=gd
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=zip

cgi.fix_pathinfo=1
fastcgi.logging = 0
