[PHP]
extension_dir = "C:/WPLaunch/core/php/ext"
date.timezone = "Europe/Kyiv"
display_errors = On
error_log = "C:/WPLaunch/logs/php_error.log"

extension=curl
extension=gd
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=zip

cgi.fix_pathinfo=1

[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.file_cache="C:/WPLaunch/tmp/opcache"
opcache.file_cache_fallback=1
opcache.memory_consumption=128
opcache.max_accelerated_files=4000
