[mysqld]
port=3306
basedir="C:/WPronto/src/WPLaunchGUI/bin/Debug/net8.0-windows/core/mysql"
datadir="C:/WPronto/src/WPLaunchGUI/bin/Debug/net8.0-windows/data/mysql"
max_allowed_packet=64M
innodb_log_file_size=128M
innodb_flush_log_at_trx_commit=2
sync_binlog=0
