[PHP]
extension_dir = "C:/WPLaunch/src/WPLaunchGUI/bin/Debug/net8.0-windows/core/php/ext"
date.timezone = "Europe/Kyiv"
display_errors = Off
error_log = "C:/WPLaunch/src/WPLaunchGUI/bin/Debug/net8.0-windows/logs/php_error.log"

upload_max_filesize = 256M
post_max_size = 256M
memory_limit = 512M
max_execution_time = 300
max_input_time = 300
max_file_uploads = 20

extension=curl
extension=gd
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=zip

cgi.fix_pathinfo=1
