[PHP]
extension_dir = "C:/WPronto/src/WPLaunchGUI/bin/Debug/net8.0-windows/core/php/ext"
date.timezone = "Europe/Kyiv"
display_errors = Off
error_log = "C:/WPronto/src/WPLaunchGUI/bin/Debug/net8.0-windows/logs/php_error.log"

upload_max_filesize = 256M
post_max_size = 256M
memory_limit = 512M
max_execution_time = 300
max_input_time = 300

extension=php_curl.dll
extension=php_gd.dll
extension=php_mbstring.dll
extension=php_mysqli.dll
extension=php_openssl.dll
extension=php_pdo_mysql.dll
extension=php_zip.dll

cgi.fix_pathinfo=1
