server {
    listen 8080;
    server_name mynewsite.wp;
    root "C:/WPronto/src/WPLaunchGUI/bin/Debug/net8.0-windows/www/mynewsite";
    index index.php;

    client_max_body_size 256M;

    location / { try_files $uri $uri/ /index.php?$args; }

    location ~ /\. { deny all; }

    location ~ \.php$ {
        try_files     $uri =404;
        fastcgi_pass  127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include       fastcgi_params;
        fastcgi_read_timeout 600;
    }
}
